server:
  port: 80

spring:
  application:
    name: gateway

#스프링 유레카 클라이언트 구축
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        default-zone: http://localhost:8761/eureka/