apiVersion: v1
kind: Service
metadata:
  name: momukji-eureka-app
  labels:
    app: webapp
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 8761
    targetPort: 8761
    protocol: TCP
    name: http
  selector:
    app: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: momukji-eureka-rs
spec:
  replicas: 3

  selector:
    matchLabels:
      app: webapp
      tier: app
  template:
    metadata:
      labels:
        app: webapp
        tier: app
    spec:
      containers:
        - name: momukji-eureka
          image: momukji-eureka:44437b6
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
              protocol: TCP
